language: ruby
jdk:
- oraclejdk8
rvm:
- 2.3.1
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
before_install:
- openssl aes-256-cbc -K $encrypted_b7fd0c4a3616_key -iv $encrypted_b7fd0c4a3616_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: DlqbIUftFozH+Cur/c7pSpRIcviauaL1cYQrZvsMSnOC5tbBSz0sT+yjlOAz0WRAOtVcaMoCdr8A+CXGxZAVnrDFLaAVykL0zvAOBDNV82FYOsdCsJlQiDaZvW0MNSNbmIxs4eDQKXxnqPl7/iUmmEQhqUkBx6V8FF2DG/nJdeuvDenhzKnI/C+M0SGW6U0iAZrSCg/0sqHZ8bi+gGLff9H60afWE/U3zJT3PrATdlKxenGpyPq/GGNeHUMpJRjXD9Zps9qU/pPCrfsZy5RTEPnYmQ047ML19qL9HX8ZTP4yPqbzkVS+rFiHJwcB/x364yDPXurI7VrBUoFKGGbv9Yo1y3nZfK/Pg8ryZj8tnO9no54uMFWQjCh639kF+iOI2vr8Rjc8f7N7ni/NbKZABN8KBRpMRT6EK1MmuF2hQeREVnyK4b+XoA06o1TSP+1VGqpdhL0mnI8OpaHdHLFQQ67uAxq2RR26eiP77XXuf6wsvxkoM6SPgRxEi4OD/3779GsBJRm+vdsJrU+XvTzTuL3SHlPh/by4QQJG9v9X9e1qE8LcLIWhal9ufVxii+5MmuxOSb9ucd6RkdpsHSVvce67wzmwe0+/hh2FJVx+/4sf5kWEG8uniuq6arXyu3S+Ygj9/AJY6iKORhXi/XagYD6RFtp/dsZWNm/VOw/qTuY=
  - secure: XOaVwvTecLcSG15omPW1NHu0UeQdN3COA1ZWeJp7d38cXNl7YZawcgm84BIFbbj9RRR1usgfQqlCGf39bsWt1f6TCez0BQnvqqdKW4O67SIekh8k3wL2Tj9Rl+qRShgFq0H5oOsmQH3EvTMt95HV6uMS4DEJdhgKRVXfhml/Jqa0OXhXDg5iEWbWAD0tE7HAClpky2P99GdKFVwMXcEqPM3q+Ni9EjQ0/Jh5vBlsvKolo1XhQInSeL3K4rF09PPUVDBfoJ7NXFMsm8dtnjx9RCfo5a0ZDE9Ly0vBICXOakqb2HCEtO1IiwyU+vH6aLRL1rs3/+yGMaiQ45GCLK5OHIR8cs4b+wNL6CsEPFZszTfwivLcbntb5zXHw0sB3+YCL4DwgH0bMvvUQ9xErKD6SzE3KmoWqEqupubtrznEGJKo+7nc3X3/E31+yKBLp/rhLdmFG2gsLoNwJVBkc7Xvw2ArU1XAle7IzPzetW0vK+P/RdeYVievcFPSgaCZVfTMYLJaERM45OKTWfsOPftKdk7e+RXxBJaXa2h0tyiBUyaDEX1ZGJprzB8YkPASWcDVKkLWyC/+8Fao2trWKzkuVdeam1HkAtYpGfP1M50DryaGUbKKtX5rap5zFJhuTNtSuyqQM22eK76OzM/prneGBRLkMaC495AvRhV5S4k8620=
  - secure: UrdekH3Lens9wEHA4Rj/lXYKtG1HUxC8avYdMebcc29VINyx+RZjOPYihuLbpFR5Ykl6IUz1YB8V9p0diWV5xE1rCoQpoBeSzyd2dnKtwsmXwOrt2gtqxy42kwOqsFo5cTYJ2Fe8BHqyX4tD0FYp5hHypJDU4aB0dCNNZ9/zDYpBqk95npku4kW7CmLLjueMZ/0fLHl7lSPjTr2qkpbLR+jFOQJNtIw22iuz3utykYwI8oieQXGZ7tQO1b887HAbMaMvGh9y3qu0TJgZrlItEuzIhNAnzF1IYrUbI7G6r9iEZWw68wAZE9ebgWhXmGCeTiYw3HPTosNh/1wMukIFZquRZMK0QZYPAcJByw0s5lsJYnUlp77NuNBxuVForuGNuwfSMktzJLuYACsp21fjQl/0/Og2GqFj9pMRaowh/DiLMsdYemd+5O6mrSAIKthaePw1+WoIRoVymIxBVkGC+B/5NqVhZhyCYQf13b7xJ2kSn6jhzgvQyeztG4/9ZHfX7Xc4mPdFsbUhQdR+XfhPcjP7jYlvoBR62/OJCR4B/9TumvUy1PUv2A0mDehD3TLZNUF/DIFO+pETSm68A4bQPfFdpqBy5c/oeq1Mu1UPTXzEvZyJ7Bv7KPI0+eYMmXkHCqbO1jrazhDd3+muy3qPtS2/GoR8a00zT2b3EGjTV/A=
